### ISSUE TITLE
Printing a Glottolog object gives a file not found error while loading Glottolog does not

### ISSUE THREAD

**Issue by d97hah** [clld/pyglottolog#8] opened 2019-05-14 19:42 UTC
In a session with several people, I saw on Python 3.7 on Macs that after these run successfully

import pyglottolog.api
gl = pyglottolog.api.Glottolog("glottolog")

This gives an file not found like error on 

print(gl)

I am sorry I can't reproduce the error on my own but I saw it happening several times and it should be traceable what files are actually sought upon print(gl)

**Comment by xrotwang** [comment] 2019-05-14 19:50
Printing means accessing the __unicode__ attribute, which tries to
determine the git hash of the clone. Presumably,  the path to the clone
wasn't valid.

But yes, file not found errors should report the paths.

d97hah <notifications@github.com> schrieb am Di., 14. Mai 2019, 21:42:

**Comment by xrotwang** [comment] 2019-05-15 12:06
And I also agree that instantiating the `Glottolog` object should already perform a couple of sanity checks like looking for a `languoids` directory.

**Comment by d97hah** [comment] 2019-05-17 19:56
In these cases I think the download (rather than clone) was actually valid,
i.e., doing various things (except print(gl)) with the gl object, including
traversing all gl.languoids() objects, worked.

Pada tanggal Rab, 15 Mei 2019 pukul 14.06 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment] 2019-06-05 11:56
I think this is a duplicate of https://github.com/clld/clldutils/issues/77 - i.e. a missing `git` executable is reported as `FileNotFoundError`.

**Closed** 2019-06-05 11:57 UTC
